eureka:
  client:
    service-url:
      defaultZone: http://localhost:8807/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: MyEureka
server:
  port: 8762
