server:
  port: 8764
spring:
  application:
    name: my-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


